services:
  proxy:
    build: nginx
    restart: always
    environment:
      - FLASK_SERVER_ADDR=backend-app:8000
    ports:
      - 1337:80
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  backend:
    build: backend
    restart: always
    expose:
      - 8000
    ports:
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/backend-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app