services:
  backend:
    build: backend
    restart: always
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
    volumes:
      - "./backend:/src"
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - frontnet

networks:
  backnet:
  frontnet: